### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by genxstylez** [vitalets/react-native-extended-stylesheet#1]
```
uncaught error Error: SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/samliu/Projects/weather/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at OptionManager.mergePresets (/Users/samliu/Projects/weather/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:28)
TransformError: /Users/samliu/Projects/weather/node_modules/react-native-extended-stylesheet/src/index.js: Unexpected token ...
See logs /var/folders/qh/1pg8d2s57k52gqxszrwf6f940000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:90:13)
    at BunserBuf.emit (events.js:182:7)
    at BunserBuf.process (/Users/samliu/Projects/weather/node_modules/bser/index.js:289:10)
    at /Users/samliu/Projects/weather/node_modules/bser/index.js:244:12
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
Command /bin/sh failed with exit code 1
```

Unexpected token

**Comment by genxstylez** [comment]
Tried with the example, and same happens.

![screen shot 2016-02-03 at 1 06 28 pm](https://cloud.githubusercontent.com/assets/1086338/12773511/4cf1e2d8-ca77-11e5-93e8-de52704adbb4.png)

**Comment by vitalets** [comment]
hi @genxstylez , thanks for reporting!
It seems that ES6 spread operator was not processed.
Could you provide your RN version ?

**Comment by genxstylez** [comment]
It's the latest version, 0.18.1?

**Comment by vitalets** [comment]
I your logs I see `node_modules/babel-core` - do you use custom babel transformation instead of react-native built-in? Could you show your package.json and .babelrc (if any)?

If init RN project from scratch `react-native init SomeProject` I have only `react-native` in `node_modules` and babel is inside, not on top level.

Anyway, If you use custom babel transformation it should be in sync with [RN .babelrc](https://github.com/facebook/react-native/tree/master/babel-preset).
Exactly for this error it looks like these plugins are missing:
http://babeljs.io/docs/plugins/transform-es2015-spread/
http://babeljs.io/docs/plugins/transform-object-rest-spread/

**Comment by genxstylez** [comment]
https://github.com/styome/shiny-winner/blob/master/package.json my package.json

**Comment by vitalets** [comment]
After deep research I found the problem: having `.babelrc` inside breaks react packager.
Please try with new version 0.1.4 it should work fine.

**Comment by genxstylez** [comment]
@vitalets thanks~ I will try it and come back here!

**Comment by vitalets** [comment]
ok. will wait for your check. Thank you!

**Comment by vitalets** [comment]
hi @genxstylez 
did you get it working?

**Comment by vitalets** [comment]
closing as I get feedback that it works now.

**Comment by genxstylez** [comment]
@vitalets sorry, was busy, didn't check, nice to hear it!
